apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

images:
  - name: jellyfin/jellyfin
    newName: jellyfin/jellyfin
    newTag: latest

resources:
  - ../../base/jellyfin/

patches:
  - path: sts-patch.yaml
    target:
      kind: StatefulSet
  - patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.100.210
    target:
      kind: Service
      name: jellyfin
      version: v1

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: jellyfin
