apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: filebrowser

resources:
  - deployment.yaml
  - service.yaml
