apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: kube-public
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: kube-public
spec:
  type: LoadBalancer
  ports:
    - name: web
      targetPort: web
      port: 80
    - name: secureweb
      targetPort: secureweb
      port: 443
  selector:
    app: traefik
