apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: filebrowser
  ports:
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 80
