apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: filebrowser

resources:
  - filebrowser-sts.yaml
  - filebrowser-svc.yaml
