apiVersion: v1
kind: Service
metadata:
  name: homarr
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: homarr
  ports:
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 7575
