apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: qbittorrent

images:
  - name: linuxserver/qbittorrent
    newName: linuxserver/qbittorrent
    newTag: latest

resources:
  - ../../base/qbittorrent/

patches:
  - path: sts-patch.yaml
    target:
      kind: StatefulSet
  # - patch: |-
  #     - op: add
  #       path: /spec/loadBalancerIP
  #       value: 192.168.100.213
  #     - op: replace
  #       path: /spec/type
  #       value: LoadBalancer
  #   target:
  #     kind: Service
  #     name: qbittorrent
  #     version: v1
