apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: homepage

resources:
  - configMap.yaml
  - serviceAccount.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - httpRoute.yaml
