apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          env:
            - name: TZ
              value: Europe/Bucharest
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: web-ui
              containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          hostPath:
            type: Directory
            path: /mnt/smg2t/config/sonarr/config
        - name: downloads
          hostPath:
            type: Directory
            path: /mnt/smg2t/media/
