apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: sonarr
  ports:
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 8989
