apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: jellyfin

resources:
  - jellyfin-sts.yaml
  - jellyfin-svc.yaml
