apiVersion: v1
kind: Service
metadata:
  name: httpbin-staging
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin-staging
  namespace: staging
spec:
  parentRefs:
    - kind: Gateway
      name: envoy-gateway
      namespace: kube-public
      sectionName: https
  hostnames:
    - "httpbin-staging.ak1pro.n1l.ro"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: httpbin-staging
          port: 80
