apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: httpbin

resources:
  - deployment.yaml
  - http-routing.yaml

configMapGenerator:
  - name: httpbin-envoy-yaml
    files:
      - envoy.yaml=envoy.yaml
  - name: httpbin-envoy-hmac
    files:
      - hmac-secret.yaml=envoy-hmac-secret.yaml
  - name: httpbin-envoy-token
    files:
      - token-secret.yaml=envoy-token-secret.yaml
