apiVersion: v1
kind: Namespace
metadata:
  labels:
    shared-gateway-access: "true"
  name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    shared-gateway-access: "true"
  name: staging
