apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: qbittorrent

resources:
  - qbittorrent-sts.yaml
  - qbittorrent-svc.yaml
