apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: staging
spec:
  type: LoadBalancer
  # loadBalancerIP: 192.168.100.145
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: web-ui
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: listener-tcp
      protocol: TCP
      port: 6881
      targetPort: 6881
    - name: listener-udp
      protocol: UDP
      port: 6881
      targetPort: 6881
